---
driver:
  name: vagrant

driver_config:
    customize:
        memory: 1024
    require_chef_omnibus: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[scalr-core::default]
    attributes:
        mysql:
            server_root_password: 'rootpass'
            server_debian_password: 'debpass'
            server_repl_password: 'replpass'
